/* eslint-disable @typescript-eslint/no-explicit-any */

import { actionOrigin } from '@DomainConstants/types/actions.types';

export interface ISaveGuideLines {
  id: string;
  nombre: string;
  idPolitica: string;
  activo: boolean;
  idMuseo: string;
}
export interface IGetGuidelinesResponse {
  id: string;
  nombre: string;
  activo: boolean;
  politica: IPolitica;
  fechaInicio?: any;
  fechaFin?: any;
  entidad?: string;
}
export interface ICeateGuidelinesResponse {
  nombre: string;
  idPolitica: string;
  activo: boolean;
  idMuseo: number;
}
export interface IEditGuidelineResponse {
  id: string;
  nombre: string;
  idPolitica: string;
  activo: boolean;
  idMuseo: number;
}
export interface IPolitica {
  id: string;
  nombre: string;
  fechaInicio: Date;
  fechaFin: Date;
  cobertura: string;
  entidad: IEntidad;
}
export interface IEvaluadoresResponse {
  id: string;
  nombre: string;
}
export interface IPoliticasResponse {
  id: string;
  nombre: string;
  fechaInicio: Date;
  fechaFin: Date;
  entidad: IEntidad;
  cobertura: string;
}
export interface IEntidad {
  id: string;
  nombre: string;
}
export interface IModalEdit {
  idEdit: boolean;
  elementSelected: any;
}
export interface IModalEditEje {
  idEdit: boolean;
  elementSelected: IEjesEstrategico;
  idPlan?: string;
}
export interface IConfirmActionModal {
  origin: actionOrigin;
  title: string;
  messages: string;
  textLink?: string;
  textButton?: string;
}
export interface IEmmitrAction {
  origin: actionOrigin;
  action: boolean;
}
export interface IStrategicPlansResponse {
  id: string;
  fechaInicio: Date;
  fechaFin: Date;
  idMuseo: number;
  ejesEstrategicos: IEjesEstrategico[];
}
export interface IEjesEstrategico {
  id: string;
  nombre: string;
  descripcion: string;
  lineamientosEstrategicos: LineamientosEstrategico[];
  acciones?: IAcciones[];
  fechaFin?: Date;
  fechaInicio?: Date;
  evaluadores?: IEvaluadoresResponse[];
}
export interface IAcciones {
  id: string;
  nombre: string;
  descripcion: string;
  indicadores: Indicadore[];
}
export interface Indicadore {
  id: string;
  nombre: string;
  peso: number;
  tipoIndicador: LineamientosEstrategico;
}
export interface LineamientosEstrategico {
  id: string;
  nombre: string;
}
export interface ICreateStrategicPlans {
  fechaInicio: string;
  fechaFin: string;
  idMuseo: number;
  ejesEstrategicos: EjesEstrategico[];
}
export interface EjesEstrategico {
  nombre: string;
  descripcion: string;
  ejeEstrategicoLineamientoEstrategico: IGuidelineList[];
  ejeEstrategicoEvaluadores: IEvaluatorList[]; // TODO CHANGE AND VERIFY URGENT DATA!!!
}
export interface IEvaluatorList {
  idEvaluador: string;
}
export interface IGuidelineList {
  idLineamientoEstrategico: string;
}

// Generated by https://quicktype.io
export interface IEditEjeEstrategico {
  id: string;
  nombre: string;
  descripcion: string;
  idPlanestrategico: string;
  ejeEstrategicoLineamientoEstrategico: EjeEstrategicoLineamientoEstrategico[];
  acciones: Acciones[];
  ejeEstrategicoEvaluadores: EjeEstrategicoEvaluadore[];
}
export interface Acciones {
  id: string;
  nombre: string;
  esNueva: boolean;
  descripcion: string;
  idEjeEstrategico: string;
  accionIndicadores: AccionIndicadore[];
}
export interface AccionIndicadore {
  idAccion: string;
  idIndicador: string;
  peso: number;
}
export interface EjeEstrategicoEvaluadore {
  idEjeEstrategico: string;
  idEvaluador: string;
}
export interface EjeEstrategicoLineamientoEstrategico {
  idEjeEstrategico: string;
  idLineamientoEstrategico: string;
}
export interface IIndicadoresResponse {
  id: string;
  nombre: string;
  formula: string;
  meta: number;
  peso: number;
  tendencia: string;
  criterio: string;
  tipoIndicador: TipoIndicador;
}
export interface TipoIndicador {
  id: string;
  nombre: string;
}

// Generated by https://quicktype.io

export interface ITypeIndicatorsRequest {
  id: string;
  nombre: string;
  indicadores: Indicadores[];
}

export interface Indicadores {
  id: string;
  idTipoIndicador: string;
  meta: number;
  nombre: string;
  formula: string;
  idUnidadDeMedida: string;
  tendencia: string;
  criterio: string;
  idCategoriaIndicador?: string;
  accionIndicadores?: AccionIndicadore[];
  proyectosAsociados?: IproyectosAsociados[];
}

export interface AccionIndicadore {
  idAccion: string;
  idIndicador: string;
  peso: number;
}

export interface IproyectosAsociados {
  idProyecto: string;
  idIndicador: string;
  numero: string;
  nombre: string;
  peso: number;
}

export interface IUnidadesMedida {
  id: string;
  nombre: string;
  indicadores?: any[];
}

export interface ITipoIndicador {
  id: string;
  nombre: string;
}

export interface ICategories {
  id: string;
  nombre: string;
  indicadores: any[];
}
