export const TOKEN = {
  AUTH_USER_USE_CASES: 'AUTH_USER_USE_CASES',
  AUTH_USER_REPOSITORY: 'AUTH_USER_REPOSITORY',
  PLANNING_USE_CASES: 'PLANNING_USE_CASES',
  PLANNING_REPOSITORY: 'PLANNING_REPOSITORY',
} as const;
